repos:
    # python import sorting - will amend files
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort

    # python code formatting - will amend files
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black

    # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
              - flake8-docstrings
              - flake8-bandit
              - flake8-print
            exclude: ^tests|migrations

    # python static type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.961
      hooks:
          - id: mypy
            additional_dependencies:
                - types-requests
