# Generated by Django 3.1.4 on 2020-12-16 13:05

from django.db import migrations, models

from linear.models import TShirtSizing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinearIssue',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(blank=True, default='', max_length=100)),
                ('milestone_name', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('estimate', models.IntegerField(choices=TShirtSizing.choices, null=True)),
                ('assignee_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
