# Generated by Django 3.1.4 on 2020-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinearTask",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=10)),
                ("team_name", models.CharField(max_length=100)),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "milestone_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("estimate", models.IntegerField(null=True)),
                ("assignee_name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
            ],
        ),
    ]
