# Generated by Django 3.1.4 on 2020-12-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearissue',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, help_text='When this issue was last refreshed from Linear, via import or webhook', null=True),
        ),
    ]
